remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme

title: OldGamesCracking
description: To unprotect and to preserve
url: https://oldgamescracking.github.io/

author:
  name: 'OldGamesCracking'
  url: https://oldgamescracking.github.io/
  email: oldgamescracking@gmail.com

show_downloads: false

collections:
  lections:
    output: true
